#!/usr/bin/env sh

set -euxo pipefail

cd "${HOME}"
git clone --bare git@github.com:Umofomia/dotfiles.git "${HOME}/.dotfiles.git"

dotfiles() {
  git --git-dir="${HOME}/.dotfiles.git" --work-tree="${HOME}" $@
}

dotfiles config --local status.showUntrackedFiles no
dotfiles checkout
