#!/usr/bin/env sh

set -eu

cd "${HOME}"
dotfiles_git_dir="${HOME}/.dotfiles.git"

git clone --bare git@github.com:Umofomia/dotfiles.git "${dotfiles_git_dir}"

dotfiles() {
  git --git-dir="${dotfiles_git_dir}" --work-tree="${HOME}" "$@"
}

dotfiles config --local status.showUntrackedFiles no
dotfiles config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
dotfiles fetch
dotfiles branch --set-upstream-to=origin/master master

if ! checkout_errors=$(dotfiles checkout 2>&1); then
  backup_dir="dotfiles-backup-$(date +%s)"
  echo "Backing up pre-existing dotfiles to ${backup_dir}..."
  for dotfile in $(printf '%s\n' "${checkout_errors}" | grep "^\t" | cut -f2); do
    echo "${dotfile}"
    mkdir -p "${backup_dir}/$(dirname "${dotfile}")"
    mv "${dotfile}" "${backup_dir}/${dotfile}"
  done
  dotfiles checkout
fi
